export const lightColors = {
  background: '#f5f5f5',
  surface: '#ffffff',
  surfaceSecondary: '#f8f9fa',
  primary: '#007AFF',
  text: '#333333',
  textSecondary: '#666666',
  textTertiary: '#999999',
  border: '#eeeeee',
  borderLight: '#f0f0f0',
  sunday: '#FF3B30',
  saturday: '#007AFF',
  today: '#E8F4FD',
  selected: '#E3F2FD',
  dragRange: '#B3E5FC',
  error: '#FF3B30',
  overlay: 'rgba(0, 0, 0, 0.4)',
  inputBackground: '#f0f0f0',
  delete: '#FF3B30',
  errorBackground: '#FFF3F3',
  onPrimary: '#ffffff',
  onEvent: '#ffffff',
  pickerHighlight: 'rgba(0, 122, 255, 0.05)',
  pickerText: '#999999',
  pickerTextSelected: '#000000',
  currentTimeIndicator: '#FF3B30',
  disabled: '#cccccc',
  allDayEvent: '#E8F4FD',
  allDayEventText: '#007AFF',
};

export const darkColors = {
  background: '#000000',
  surface: '#1c1c1e',
  surfaceSecondary: '#2c2c2e',
  primary: '#0A84FF',
  text: '#ffffff',
  textSecondary: '#ababab',
  textTertiary: '#8e8e93',
  border: '#38383a',
  borderLight: '#2c2c2e',
  sunday: '#FF453A',
  saturday: '#0A84FF',
  today: '#1c3a4d',
  selected: '#1c3a4d',
  dragRange: '#1c3a4d',
  error: '#FF453A',
  overlay: 'rgba(0, 0, 0, 0.6)',
  inputBackground: '#2c2c2e',
  delete: '#FF453A',
  errorBackground: '#3a1c1c',
  onPrimary: '#ffffff',
  onEvent: '#ffffff',
  pickerHighlight: 'rgba(10, 132, 255, 0.1)',
  pickerText: '#8e8e93',
  pickerTextSelected: '#ffffff',
  currentTimeIndicator: '#FF453A',
  disabled: '#48484a',
  allDayEvent: '#1c3a4d',
  allDayEventText: '#0A84FF',
};

export type ThemeColors = typeof lightColors;

// Skin definitions
export interface SkinDefinition {
  id: string;
  nameKey: string; // i18n key
  isPremium: boolean;
  light: Partial<ThemeColors>;
  dark: Partial<ThemeColors>;
}

export const SKINS: SkinDefinition[] = [
  {
    id: 'default',
    nameKey: 'skinDefault',
    isPremium: false,
    light: {},
    dark: {},
  },
  {
    id: 'rose',
    nameKey: 'skinRose',
    isPremium: true,
    light: {
      primary: '#E91E63',
      saturday: '#E91E63',
      today: '#FCE4EC',
      selected: '#F8BBD0',
      dragRange: '#F8BBD0',
      allDayEvent: '#FCE4EC',
      allDayEventText: '#E91E63',
    },
    dark: {
      primary: '#F06292',
      saturday: '#F06292',
      today: '#3a1c2e',
      selected: '#3a1c2e',
      dragRange: '#3a1c2e',
      allDayEvent: '#3a1c2e',
      allDayEventText: '#F06292',
    },
  },
  {
    id: 'ocean',
    nameKey: 'skinOcean',
    isPremium: true,
    light: {
      primary: '#00897B',
      saturday: '#00897B',
      today: '#E0F2F1',
      selected: '#B2DFDB',
      dragRange: '#B2DFDB',
      allDayEvent: '#E0F2F1',
      allDayEventText: '#00897B',
    },
    dark: {
      primary: '#4DB6AC',
      saturday: '#4DB6AC',
      today: '#1c3a36',
      selected: '#1c3a36',
      dragRange: '#1c3a36',
      allDayEvent: '#1c3a36',
      allDayEventText: '#4DB6AC',
    },
  },
  {
    id: 'lavender',
    nameKey: 'skinLavender',
    isPremium: true,
    light: {
      primary: '#7C4DFF',
      saturday: '#7C4DFF',
      today: '#EDE7F6',
      selected: '#D1C4E9',
      dragRange: '#D1C4E9',
      allDayEvent: '#EDE7F6',
      allDayEventText: '#7C4DFF',
    },
    dark: {
      primary: '#B388FF',
      saturday: '#B388FF',
      today: '#2a1c4d',
      selected: '#2a1c4d',
      dragRange: '#2a1c4d',
      allDayEvent: '#2a1c4d',
      allDayEventText: '#B388FF',
    },
  },
  {
    id: 'sunset',
    nameKey: 'skinSunset',
    isPremium: true,
    light: {
      primary: '#FF6D00',
      saturday: '#FF6D00',
      today: '#FFF3E0',
      selected: '#FFE0B2',
      dragRange: '#FFE0B2',
      allDayEvent: '#FFF3E0',
      allDayEventText: '#FF6D00',
    },
    dark: {
      primary: '#FFAB40',
      saturday: '#FFAB40',
      today: '#3a2a1c',
      selected: '#3a2a1c',
      dragRange: '#3a2a1c',
      allDayEvent: '#3a2a1c',
      allDayEventText: '#FFAB40',
    },
  },
];
