const URL='https://llxmsbnqtdlqypnwapzz.supabase.co',KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxseG1zYm5xdGRscXlwbndhcHp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4MjA5MjEsImV4cCI6MjA1MzM5NjkyMX0.EkqepILQU0KgOTW1ZaXpe54ERpZbSRodf24r5022VKs';
const $=s=>document.querySelector(s),rpc=async(fn,body)=>{const r=await fetch(`${URL}/rest/v1/rpc/${fn}`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw Error(await r.text());return r.json()};
const randomHex=n=>{const b=new Uint8Array(n/2);crypto.getRandomValues(b);return [...b].map(x=>x.toString(16).padStart(2,'0')).join('')};
let code=new URLSearchParams(location.search).get('code')||localStorage.shareCode||'',me=JSON.parse(localStorage.shareMe||'null'),data={events:[],members:[]},month=new Date(new Date().getFullYear(),new Date().getMonth(),1),editing=null,ws;
$('#code').value=code;if(me)$('#name').value=me.name;const member=()=>{if(!me){me={id:randomHex(16),secret:randomHex(32),shareCode:code,name:$('#name').value.trim(),emoji:'',color:'#007AFF',updatedAt:new Date().toISOString()};localStorage.shareMe=JSON.stringify(me)}return me};
async function pull(){data=await rpc('calendar_share_pull',{p_code:code,p_since:'-infinity',p_member:member()});if(!data)throw Error('not found');render();if(editing)loadSocial()}
async function open(){try{code=$('#code').value.trim().toLowerCase();if(!/^[a-f0-9]{32}$/.test(code)||!$('#name').value.trim())throw Error('招待コードと表示名を入力してください');if(me?.shareCode!==code)me=null;else{me.name=$('#name').value.trim();me.updatedAt=new Date().toISOString();localStorage.shareMe=JSON.stringify(me)}member();localStorage.shareCode=code;history.replaceState(null,'',`?code=${code}`);await pull();$('#join').hidden=true;$('#app').hidden=false;connect()}catch(e){$('#error').textContent='共有カレンダーを開けませんでした'}}
const isViewer=()=>data.members?.find(x=>x.member_id===me?.id)?.role==='viewer';
function render(){const y=month.getFullYear(),m=month.getMonth(),first=new Date(y,m,1).getDay();$('#add').hidden=isViewer();$('#month').textContent=`${data.calendar?.emoji||''} ${data.calendar?.name||''}　${y}年${m+1}月`;$('#weekdays').innerHTML='日月火水木金土'.split('').map(x=>`<div>${x}</div>`).join('');let html='';for(let i=0;i<42;i++){const n=i-first+1,d=new Date(y,m,n),key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,out=d.getMonth()!==m,today=new Date().toDateString()===d.toDateString(),evs=(data.events||[]).filter(e=>!e.deleted&&e.start_date<=key&&e.end_date>=key);html+=`<div class="day ${out?'out':''} ${today?'today':''}" data-date="${key}"><span>${d.getDate()}</span>${evs.map(e=>`<button class="ev" data-id="${e.id}">${escapeHtml(e.title)}</button>`).join('')}</div>`}$('#grid').innerHTML=html;document.querySelectorAll('.day').forEach(x=>x.onclick=e=>{const id=e.target.dataset.id;if(id)return showEvent(data.events.find(v=>v.id===id));if(!isViewer())showNew(x.dataset.date)})}
const escapeHtml=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const local=d=>new Date(d-Date.parse(new Date(d).toISOString().slice(0,-1))).toISOString().slice(0,16);
function showNew(day=new Date().toISOString().slice(0,10)){editing=null;$('#eventHeading').textContent='予定を追加';$('#title').value='';$('#memo').value='';$('#start').value=`${day}T12:00`;$('#end').value=`${day}T13:00`;$('#social').hidden=true;$('#event').showModal()}
function showEvent(e){editing=e;$('#eventHeading').textContent=isViewer()?'予定':'予定を編集';$('#title').value=e.title;$('#memo').value=e.memo||'';$('#start').value=new Date(`${e.start_date}T${e.start_time||'00:00'}`).toISOString().slice(0,16);$('#end').value=new Date(`${e.end_date}T${e.end_time||'23:59'}`).toISOString().slice(0,16);['#title','#memo','#start','#end'].forEach(s=>$(s).disabled=isViewer());$('#save').hidden=isViewer();$('#photo').hidden=isViewer();$('#comment').hidden=isViewer();$('#send').hidden=isViewer();$('#social').hidden=false;$('#event').showModal();loadSocial()}
async function save(e){e.preventDefault();const s=new Date($('#start').value),en=new Date($('#end').value),ev={id:editing?.id||`web-${Date.now()}-${randomHex(3)}`,title:$('#title').value.trim()||'無題',startDate:s.toISOString().slice(0,10),endDate:en.toISOString().slice(0,10),allDay:false,startTime:s.toTimeString().slice(0,5),endTime:en.toTimeString().slice(0,5),memo:$('#memo').value.trim()||null,creatorId:editing?.creator_id||me.id,updatedAt:new Date().toISOString(),deleted:false};await rpc('calendar_share_push',{p_code:code,p_calendar:null,p_events:[ev],p_member:me});$('#event').close();await pull()}
async function action(a,p){const x=await rpc('calendar_share_event_action',{p_code:code,p_event_id:editing.id,p_member_id:me.id,p_secret:me.secret,p_action:a,p_payload:p});paintSocial(x)}async function loadSocial(){if(editing)paintSocial(await rpc('calendar_share_event_context',{p_code:code,p_event_id:editing.id}))}
function paintSocial(x){const names=new Map((data.members||[]).map(m=>[m.member_id,m.name]));$('#comments').innerHTML=(x.comments||[]).map(c=>`<div class="comment"><small>${escapeHtml(names.get(c.member_id)||'メンバー')}</small>${escapeHtml(c.body)}</div>`).join('');$('#photos').innerHTML=(x.photos||[]).map(p=>`<img src="data:${p.mime_type};base64,${p.data_base64}">`).join('');$('#activity').innerHTML=(x.activity||[]).map(a=>`<p>${escapeHtml(names.get(a.member_id)||'メンバー')}・${escapeHtml(a.action)}・${new Date(a.created_at).toLocaleString()}</p>`).join('');document.querySelectorAll('#attendance button').forEach(b=>b.classList.toggle('on',(x.attendance||[]).some(a=>a.member_id===me.id&&a.status===b.dataset.s)))}
function connect(){ws?.close();ws=new WebSocket(`${URL.replace('https','wss')}/realtime/v1/websocket?apikey=${KEY}&vsn=1.0.0`);const topic=`realtime:calendar:${code}`;ws.onopen=()=>ws.send(JSON.stringify({topic,event:'phx_join',payload:{config:{broadcast:{ack:false,self:false},presence:{enabled:false},private:false}},ref:'1',join_ref:'1'}));ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.topic===topic&&m.event==='broadcast'&&m.payload?.event==='changed')pull()};ws.onclose=()=>setTimeout(connect,2000)}
$('#open').onclick=open;$('#prev').onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()-1,1);render()};$('#next').onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()+1,1);render()};$('#add').onclick=()=>showNew();$('#save').onclick=save;$('#send').onclick=()=>{const v=$('#comment').value.trim();if(v)action('comment',{body:v}).then(()=>$('#comment').value='')};document.querySelectorAll('#attendance button').forEach(b=>b.onclick=()=>action('attendance',{status:b.dataset.s}));$('#photo').onchange=async e=>{for(const f of e.target.files){const b=await new Promise(r=>{const q=new FileReader;q.onload=()=>r(q.result.split(',')[1]);q.readAsDataURL(f)});await action('photo',{mimeType:f.type||'image/jpeg',base64:b})}};if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');if(code&&me){$('#join').hidden=true;$('#app').hidden=false;pull().then(connect).catch(()=>{$('#join').hidden=false;$('#app').hidden=true})}
